name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # เปลี่ยนตามชื่อ branch ที่ต้องการ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_SERVER }} "cd //var/www/project-2-peanut-butter-and-jelly-frontend && git pull && docker-compose up -d"