name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Branch to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_SERVER }} "
            echo 'Current directory:'
            pwd
            echo 'Listing contents of /var/www:'
            ls /var/www
            cd /var/www || mkdir -p /var/www && cd /var/www;
            if [ ! -d project-2-peanut-butter-and-jelly-frontend ]; then
              git clone https://github.com/chartchai-class/project-2-peanut-butter-and-jelly-frontend project-2-peanut-butter-and-jelly-frontend
            else
              cd project-2-peanut-butter-and-jelly-frontend && git pull
            fi
            cd project-2-peanut-butter-and-jelly-frontend && docker-compose up -d
          "
